SELECT T1.ID, T1.NO, T1.OBJNO, T1.OBJTYPE, T2.NO AS MATNR, T2.WERKS, SUBSTR(T1.OBJNO,2,1£©
FROM PBOMPKG T1 
INNER JOIN PARTLIB T2 ON T1.ID = T2.PBOMPKGID
WHERE T1.OBJTYPE = 'SIPM4' AND REGEXP_LIKE(T1.OBJNO,'^[DPJ]T') --AND SUBSTR(T1.OBJNO,2,1£© = 'T' --AND T1.ID = '' 
ORDER BY T1.OBJNO DESC;procedure




